version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: campusparty-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - campus-network

volumes:
  pgdata:

networks: